name: ANT

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Specify the JDK distribution
          java-version: '11'

      - name: Build with Ant
        run: ant build

      - name: Test with Ant
        run: ant test
